- name: Install httpd package
  ansible.builtin.dnf:
    name: httpd
    state: present
    update_cache: yes
  
- name: Start service httpd, if not started
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes